### ISSUE TITLE
Problems on addWords

### ISSUE THREAD

**Issue by danielmedina** [rodgeraraujo/profanity#1]
Hello.

I'm trying to test your lib but I'm having some issues with addWords feature.

when I use like this (like the example on your readme file), your library crashes
`profanity.addWords(['bola', 'joana']);`
Error: 
```
ERROR TypeError: word.replace is not a function
    at /home/runner/Profanaty-test/node_modules/profanity-js/dist/src/index.js:114:49
    at Array.filter (<anonymous>)
    at Profanity.isProfane (/home/runner/Profanaty-test/node_modules/profanity-js/dist/src/index.js:112:30)
    at /home/runner/Profanaty-test/index.js:33:28
    at Array.forEach (<anonymous>)
    at /home/runner/Profanaty-test/index.js:22:11
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

but when I try like this, works well
`profanity.addWords('bola', 'joana')`

I created an repl.it to show you the error
https://repl.it/talk/share/Profanity-lib/129244

**Comment by rodgeraraujo** [comment]
Hi,

The `.addWords()` accept only a list os strings. In the example on readme have a little mistake, I will fix this, see bellow how function works:

```js
profanity.addWords('you', 'beautiful', 'baby')

//or
const badWords = ['you', 'beautiful', 'baby']
profanity.addWords(...badWords)
```

For more details see test folder

**Comment by rodgeraraujo** [comment]
> Hello.
> 
> I'm trying to test your lib but I'm having some issues with addWords feature.
> 
> when I use like this (like the example on your readme file), your library crashes
> `profanity.addWords(['bola', 'joana']);`
> Error:
> 
> ```
> ERROR TypeError: word.replace is not a function
>     at /home/runner/Profanaty-test/node_modules/profanity-js/dist/src/index.js:114:49
>     at Array.filter (<anonymous>)
>     at Profanity.isProfane (/home/runner/Profanaty-test/node_modules/profanity-js/dist/src/index.js:112:30)
>     at /home/runner/Profanaty-test/index.js:33:28
>     at Array.forEach (<anonymous>)
>     at /home/runner/Profanaty-test/index.js:22:11
>     at Script.runInContext (vm.js:130:18)
>     at Object.<anonymous> (/run_dir/interp.js:209:20)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> ```
> 
> but when I try like this, works well
> `profanity.addWords('bola', 'joana')`
> 
> I created an repl.it to show you the error
> https://repl.it/talk/share/Profanity-lib/129244

Hi,

The `.addWords()` accept only a list os strings. In the example on readme have a little mistake, I will fix this, see bellow how function works:

```js
profanity.addWords('you', 'beautiful', 'baby')

//or
const badWords = ['you', 'beautiful', 'baby']
profanity.addWords(...badWords)
```

For more details see test folder

**Comment by danielmedina** [comment]
Hi.

You're right! Sorry, dude. Just started to work serious with javascript and node.

If you accept a sugestion, I'm doing a "pre-treatment" of my string to avoid some cases that your library don't get.

This removes anything that is not a letter, number or accented letter and deals with leet code as we use it in Brazil. Idk if it is the more effective or the good way to do this, but it worked.

```
let cleanedWord = word.replace(/[^a-z0-9À-ž\s]/gi, '')
      .replace(/1/g, 'l')
      .replace(/3/g, 'e')
      .replace(/4/g, 'a')
      .replace(/5/g, 's')
      .replace(/7/g, 't')
      .replace(/0/g, 'o');    
```

**Comment by rodgeraraujo** [comment]
> Hi.
> 
> You're right! Sorry, dude. Just started to work serious with javascript and node.
> 
> ‎Se você aceitar uma sugestão, eu estou fazendo um "pré-tratamento" da minha corda para evitar alguns casos que sua biblioteca não recebe.‎
> 
> ‎Isso remove qualquer coisa que não seja uma letra, número ou letra acentuada e lida com código leet como usamos no Brasil. Idk se é a maneira mais eficaz ou a boa maneira de fazer isso, mas funcionou.‎
> 
> ```
> let cleanedWord = word.replace(/[^a-z0-9À-ž\s]/gi, '')
>       .replace(/1/g, 'l')
>       .replace(/3/g, 'e')
>       .replace(/4/g, 'a')
>       .replace(/5/g, 's')
>       .replace(/7/g, 't')
>       .replace(/0/g, 'o');    
> ```

You are right, when I was implementing it I was not able to do this reverse treatment, since I needed to sanitize the result. 

If you want to contribute to a project and make it better, feel free to fork and contribute.

**Comment by rodgeraraujo** [comment]
> Hi.
> 
> You're right! Sorry, dude. Just started to work serious with javascript and node.
> 
> If you accept a sugestion, I'm doing a "pre-treatment" of my string to avoid some cases that your library don't get.
> 
> This removes anything that is not a letter, number or accented letter and deals with leet code as we use it in Brazil. Idk if it is the more effective or the good way to do this, but it worked.
> 
> ```
> let cleanedWord = word.replace(/[^a-z0-9À-ž\s]/gi, '')
>       .replace(/1/g, 'l')
>       .replace(/3/g, 'e')
>       .replace(/4/g, 'a')
>       .replace(/5/g, 's')
>       .replace(/7/g, 't')
>       .replace(/0/g, 'o');    
> ```

You are right, when I was implementing it I was not able to do this reverse treatment, since I needed to sanitize the result. 

If you want to contribute to a project and make it better, feel free to fork and contribute.
